import Head from "next/head";
import { useRouter } from "next/router";

export default function Details({ data }) {
  // const router = useRouter();
  // const { slug } = router.query;
  //console.log(slug);
  console.log(data)
  return (
    <div>
      <Head>
        <title>{data.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap"
          rel="stylesheet"
        />
      </Head>

      <h1>Name: {data.name} </h1>
      <p>Weight: {data.weight}</p>
      <p>Base Experience: {data.base_experience}</p>
    </div>
  );
}


export async function getServerSideProps(context) {
  const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${context.params.slug}`);
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }
  return {
    props: { data },
  };
}